# config/config.yaml

# 資料庫連線設定（SQLAlchemy URI 格式）
database:
  url: postgresql://user:password@localhost:5432/stockdb

# 檔案路徑設定
paths:
  raw_data: ./data/raw
  processed_data: ./data/processed
  sqlite: db/stockDB.db
  price_data: ./data/price    # 新增：技術指標要用的股價 CSV 存放位置
  stock_list: "data/stock_id/stock_id.csv"

# TWSE API URL 範本
twse:
  url_template: "https://www.twse.com.tw/exchangeReport/MI_INDEX?response=csv&date={date}&type=ALLBUT0999"

# TPEx API URL 範本
tpex:
  url_template: "https://www.tpex.org.tw/www/zh-tw/emerging/dailyDl?name=EMdes010.{date}-C.csv"

# ticket（融券／借券 HTML）URL 範本
ticket:
  # TWSE 融券／借券
  twse_url_template: "https://www.twse.com.tw/rwd/zh/marginTrading/TWT93U?date={date}&response=html"
  # TPEx 融券／借券
  tpex_url_template: "https://www.tpex.org.tw/www/zh-tw/margin/sbl?date={date_url}&id=&response=html"

# 日誌等級
logging:
  level: INFO

# TWSE 三大法人 API URL 範本
twse_institutional:
  url_template: "https://www.twse.com.tw/fund/T86?response=csv&date={date}&selectType=ALLBUT0999"

# TPEx 三大法人 API URL 範本
tpex_institutional:
  url_template: "https://www.tpex.org.tw/web/stock/3insti/daily_trade/3itrade_hedge_download.php?l=zh-tw&d={roc_date}"

# TWSE 殖利率／PB API URL 範本
twse_pe:
  url_template: "https://www.twse.com.tw/exchangeReport/BWIBBU_d?response=csv&date={date}&selectType=ALL"
  table_name: "twse_pe"

credit:
  twse:
    url_template: "https://www.twse.com.tw/exchangeReport/MI_MARGN?response=csv&date={date}&selectType=ALL"
  tpex:
    url_template: "https://www.tpex.org.tw/www/zh-tw/margin/balance?date={date_url}&id=&response=csv-u8"

# 財報資料設定
finance:
  table_name: finance_statements
  report_dates:
    - "2024-03-31"
    - "2024-06-30"
    - "2024-09-30"
    - "2024-12-31"

# 新增：技術指標（Technical Indicator）參數設定
technical_indicator:
  # RSI 計算要用幾天
  RSI_period: 14
  # MACD 快線、慢線與訊號線參數
  MACD_fast: 12
  MACD_slow: 26
  MACD_signal: 9
  # 布林通道參數：n 表示移動平均天數，k 表示標準差倍數
  Bollinger_N: 20
  Bollinger_k: 2
  # KD 隨機指標參數：period 表示看幾天高低價；smooth_k、smooth_d 表示 K、D 的平滑天數
  KD_period: 9
  KD_smooth_k: 3
  KD_smooth_d: 3
